apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: wasmcloud-template
  annotations:
    description: 'A wasmCloud template project for multiple components in a single repo'
spec:
  components:
    - name: endpoint
      type: component
      properties:
        image: file://./components/endpoint/build/endpoint_s.wasm
        # image: ghcr.io/jamesstocktonj1/wasmcloud-template/component-endpoint:main
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target: greeting
            namespace: jamesstocktonj1
            package: wasmcloud-template
            interfaces: [connect]

    - name: greeting
      type: component
      properties:
        image: file://./components/greeting/build/greeting_s.wasm
        # image: ghcr.io/jamesstocktonj1/wasmcloud-template/component-greeting:main
        config:
          - name: greeting-config
            properties:
              format: "New %s, %s!"
      traits:
        - type: spreadscaler
          properties:
            instances: 1

    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.23.2
      traits:
        - type: link
          properties:
            target: endpoint
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 0.0.0.0:8080
