name: Component Build

on:
  push:
    branches:
      - main
    paths:
      - components/**
      - .github/workflows/build.yaml
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  changed-components:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      components: ${{ steps.changed-components.outputs.changed_components }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-components
        uses: ./components
        with:
          matrix: true
      - name: List all changed files
        run: echo '${{ steps.changed-components.outputs.changed_components }}'

  build-components:
    name: Build Components
    needs: changed-components
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJSON(needs.changed-files.outputs.components) }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup wash-cli
        uses: wasmCloud/common-actions/install-wash@main
      - name: Setup TinyGo
        uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: '0.34.0'
      - name: Setup wasm-tools
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: wasm-tools@1.221.2

      - name: Build Component
        run: wash build -p components/${{ matrix.component }}
      - name: Publish Component
        env:
          WASH_REG_USER: ${{ github.actor }}
          WASH_REG_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: wash push ghcr.io/${{ github.repository }}/component-${{ matrix.component }}:${{ steps.meta.outputs.tags || 'main' }} components/${{ matrix.component }}/build/${{ matrix.component }}_s.wasm